### ISSUE TITLE
mesh permission?

### ISSUE THREAD

**Issue by gavanderhoorn** [sezan92/Fanuc#1]
Hi, thanks for making this available.

A quick question though: did you get any special permission from Fanuc to create these detailed models of the robot? I've created a few of these packages myself and am not allowed to use the SolidWorks models in this manner.

Just curious.

**Comment by sezan92** [comment]
thanks for your question. They already have open sourced their mesh files   [here](https://github.com/ros-industrial/fanuc/tree/indigo-devel/fanuc_lrmate200ic_support/meshes/lrmate200ic) .  Moreover I used the solidworks model available [here](https://grabcad.com/library/fanuc-lr-mate-200id-1) to generate my own meshes

**Comment by gavanderhoorn** [comment]
@sezan92 wrote:
> They already have open sourced their mesh files [here](https://github.com/ros-industrial/fanuc/tree/indigo-devel/fanuc_lrmate200ic_support/meshes/lrmate200ic).

Those are my packages :), it's also the 200iC (not D) and Fanuc was not involved in that.

> Moreover I used the solidworks model available [here](https://grabcad.com/library/fanuc-lr-mate-200id-1) to generate my own meshes

Right, ok. Grabcad. So technically no permission then, as the grabcad uploaders are also (most likely) violating their agreement with Fanuc.

**Comment by sezan92** [comment]
you said you're not allowed to use solidworks model in this manner. So how have you generated the mesh files which should have been generated from cad files.

can you show me some agreements showing such cad models violate any agreement? at the time of uploading,  I wasn't aware of.  If you can share with me, I am happy to take this repo down :)

**Comment by gavanderhoorn** [comment]
@sezan92 wrote:
> you said you're not allowed to use solidworks model in this manner

I should have been more clear: we're allowed to release *convex hulls*, not the detailed models that you include in this repository.

> can you show me some agreements showing such cad models violate any agreement?

No I can't. Thing is, you can officially only acquire these models by buying a Fanuc robot or requesting them from Fanuc. IIRC, the CRC (and the Japanese webstore) make you agree to a user license that, IIRC again, prohibits you from redistributing the models.

Technically, not finding a license with some files on the internet (ie: on grabcad) means: you can't use it until the licensing terms are cleared up.

I realise that is not a popular or common way to go about this, but Fanuc has been rather strict about it in the past. I also realise that there are numerous sites that do offer the detailed models though, no need to take your repository off-line.

I'm not a Fanuc employee, just another user and I was wondering whether you had made any deals with them, as I would've been interested in that case.

**Comment by sezan92** [comment]
I am not clear about what you mean by convex hulls and detailed models.. can you clarify about it?
the reason why I want to take this down if it violates agreement with them,  is because my faith requires to be strict about agreements and contracts, otherwise I will have to answer to God on the day of judgement. That's why I am more concerned. I will try to contact fanuc if its required God willing.

**Comment by gavanderhoorn** [comment]
@sezan92 wrote:
> I am not clear about what you mean by convex hulls and detailed models.. can you clarify about it?

This is what the LR Mate 200iD looks like as a convex hull:

![rviz_screenshot_2018_04_15-11_07_54](https://user-images.githubusercontent.com/4550046/38776812-80c140d8-409d-11e8-8ec8-1685e9734f6b.png)

Notice the difference in detail (ie: lack of) with the screenshot you show in your readme.

A convex hull is essentially a very crude approximation of the original mesh geometry, hiding any surface detail behind an outer shell.

> the reason why I want to take this down if it violates agreement with them, is because my faith requires to be strict about agreements and contracts, otherwise I will have to answer to God on the day of judgement. That's why I am more concerned. I will try to contact fanuc if its required God willing.

That is of course up to you.

As long as it's clear that I'm not requesting you to do anything.

As I wrote, I was just curious.

**Comment by sezan92** [comment]
thanks for clarifying.
